package com.cts.localtour.entity;
// Generated 2016-4-13 14:01:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Businesstypetable generated by hbm2java
 */
@Entity
@Table(name = "businesstypetable", catalog = "localtour")
public class BusinessTypeTable implements java.io.Serializable {

	private Integer id;
	private String tourTypeName;
	private int enable;

	public BusinessTypeTable() {
	}

	public BusinessTypeTable(String tourTypeName, int enable) {
		this.tourTypeName = tourTypeName;
		this.enable = enable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tourTypeName", nullable = false, length = 8)
	public String getTourTypeName() {
		return this.tourTypeName;
	}

	public void setTourTypeName(String tourTypeName) {
		this.tourTypeName = tourTypeName;
	}

	@Column(name = "enable", nullable = false)
	public int getEnable() {
		return this.enable;
	}

	public void setEnable(int enable) {
		this.enable = enable;
	}

}
