package com.cts.localtour.entity;
// Generated 2016-7-6 15:38:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DepartTable generated by hbm2java
 */
@Entity
@Table(name = "departTable", catalog = "localtour")
public class DepartTable implements java.io.Serializable {

	private DepartTableId id;

	public DepartTable() {
	}

	public DepartTable(DepartTableId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false)),
			@AttributeOverride(name = "tourId", column = @Column(name = "tourID", nullable = false)),
			@AttributeOverride(name = "destId", column = @Column(name = "destID", nullable = false)),
			@AttributeOverride(name = "departTraffic", column = @Column(name = "departTraffic", nullable = false, length = 4)),
			@AttributeOverride(name = "departTime", column = @Column(name = "departTime", nullable = false, length = 10)),
			@AttributeOverride(name = "departTrafficNo", column = @Column(name = "departTrafficNO", nullable = false, length = 8)),
			@AttributeOverride(name = "departRegionId", column = @Column(name = "departRegionID", nullable = false)) })
	public DepartTableId getId() {
		return this.id;
	}

	public void setId(DepartTableId id) {
		this.id = id;
	}

}
