package com.cts.localtour.entity;
// Generated 2016-7-6 15:38:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DepartTableId generated by hbm2java
 */
@Embeddable
public class DepartTableId implements java.io.Serializable {

	private int id;
	private int tourId;
	private int destId;
	private String departTraffic;
	private Date departTime;
	private String departTrafficNo;
	private int departRegionId;

	public DepartTableId() {
	}

	public DepartTableId(int id, int tourId, int destId, String departTraffic, Date departTime, String departTrafficNo,
			int departRegionId) {
		this.id = id;
		this.tourId = tourId;
		this.destId = destId;
		this.departTraffic = departTraffic;
		this.departTime = departTime;
		this.departTrafficNo = departTrafficNo;
		this.departRegionId = departRegionId;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tourID", nullable = false)
	public int getTourId() {
		return this.tourId;
	}

	public void setTourId(int tourId) {
		this.tourId = tourId;
	}

	@Column(name = "destID", nullable = false)
	public int getDestId() {
		return this.destId;
	}

	public void setDestId(int destId) {
		this.destId = destId;
	}

	@Column(name = "departTraffic", nullable = false, length = 4)
	public String getDepartTraffic() {
		return this.departTraffic;
	}

	public void setDepartTraffic(String departTraffic) {
		this.departTraffic = departTraffic;
	}

	@Column(name = "departTime", nullable = false, length = 10)
	public Date getDepartTime() {
		return this.departTime;
	}

	public void setDepartTime(Date departTime) {
		this.departTime = departTime;
	}

	@Column(name = "departTrafficNO", nullable = false, length = 8)
	public String getDepartTrafficNo() {
		return this.departTrafficNo;
	}

	public void setDepartTrafficNo(String departTrafficNo) {
		this.departTrafficNo = departTrafficNo;
	}

	@Column(name = "departRegionID", nullable = false)
	public int getDepartRegionId() {
		return this.departRegionId;
	}

	public void setDepartRegionId(int departRegionId) {
		this.departRegionId = departRegionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartTableId))
			return false;
		DepartTableId castOther = (DepartTableId) other;

		return (this.getId() == castOther.getId()) && (this.getTourId() == castOther.getTourId())
				&& (this.getDestId() == castOther.getDestId())
				&& ((this.getDepartTraffic() == castOther.getDepartTraffic())
						|| (this.getDepartTraffic() != null && castOther.getDepartTraffic() != null
								&& this.getDepartTraffic().equals(castOther.getDepartTraffic())))
				&& ((this.getDepartTime() == castOther.getDepartTime()) || (this.getDepartTime() != null
						&& castOther.getDepartTime() != null && this.getDepartTime().equals(castOther.getDepartTime())))
				&& ((this.getDepartTrafficNo() == castOther.getDepartTrafficNo())
						|| (this.getDepartTrafficNo() != null && castOther.getDepartTrafficNo() != null
								&& this.getDepartTrafficNo().equals(castOther.getDepartTrafficNo())))
				&& (this.getDepartRegionId() == castOther.getDepartRegionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getTourId();
		result = 37 * result + this.getDestId();
		result = 37 * result + (getDepartTraffic() == null ? 0 : this.getDepartTraffic().hashCode());
		result = 37 * result + (getDepartTime() == null ? 0 : this.getDepartTime().hashCode());
		result = 37 * result + (getDepartTrafficNo() == null ? 0 : this.getDepartTrafficNo().hashCode());
		result = 37 * result + this.getDepartRegionId();
		return result;
	}

}
