package com.cts.localtour.entity;
// Generated 2016-5-31 15:52:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GuideTable generated by hbm2java
 */
@Entity
@Table(name = "guideTable", catalog = "localtour")
public class GuideTable implements java.io.Serializable {

	private Integer id;
	private int userId;
	private Integer tourId;
	private Date startDate;
	private Date endDate;
	private boolean enable;

	public GuideTable() {
	}

	public GuideTable(int userId, boolean enable) {
		this.userId = userId;
		this.enable = enable;
	}

	public GuideTable(int userId, Integer tourId, Date startDate, Date endDate, boolean enable) {
		this.userId = userId;
		this.tourId = tourId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.enable = enable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "tourID")
	public Integer getTourId() {
		return this.tourId;
	}

	public void setTourId(Integer tourId) {
		this.tourId = tourId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "enable", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

}
