package com.cts.localtour.entity;
// Generated 2016-7-6 15:38:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvoiceTableId generated by hbm2java
 */
@Embeddable
public class InvoiceTableId implements java.io.Serializable {

	private int id;
	private int incomeId;
	private String invoiceName;
	private String invoiceContent;
	private int invoiceNo;
	private int requestUserId;
	private float invoiceAmount;
	private Date openDate;
	private int openUserId;
	private int isLend;

	public InvoiceTableId() {
	}

	public InvoiceTableId(int id, int incomeId, String invoiceName, String invoiceContent, int invoiceNo,
			int requestUserId, float invoiceAmount, Date openDate, int openUserId, int isLend) {
		this.id = id;
		this.incomeId = incomeId;
		this.invoiceName = invoiceName;
		this.invoiceContent = invoiceContent;
		this.invoiceNo = invoiceNo;
		this.requestUserId = requestUserId;
		this.invoiceAmount = invoiceAmount;
		this.openDate = openDate;
		this.openUserId = openUserId;
		this.isLend = isLend;
	}

	@Column(name = "Id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "incomeId", nullable = false)
	public int getIncomeId() {
		return this.incomeId;
	}

	public void setIncomeId(int incomeId) {
		this.incomeId = incomeId;
	}

	@Column(name = "invoiceName", nullable = false, length = 40)
	public String getInvoiceName() {
		return this.invoiceName;
	}

	public void setInvoiceName(String invoiceName) {
		this.invoiceName = invoiceName;
	}

	@Column(name = "invoiceContent", nullable = false, length = 10)
	public String getInvoiceContent() {
		return this.invoiceContent;
	}

	public void setInvoiceContent(String invoiceContent) {
		this.invoiceContent = invoiceContent;
	}

	@Column(name = "invoiceNo", nullable = false)
	public int getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(int invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "requestUserId", nullable = false)
	public int getRequestUserId() {
		return this.requestUserId;
	}

	public void setRequestUserId(int requestUserId) {
		this.requestUserId = requestUserId;
	}

	@Column(name = "invoiceAmount", nullable = false, precision = 12, scale = 0)
	public float getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(float invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Column(name = "openDate", nullable = false, length = 10)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@Column(name = "openUserId", nullable = false)
	public int getOpenUserId() {
		return this.openUserId;
	}

	public void setOpenUserId(int openUserId) {
		this.openUserId = openUserId;
	}

	@Column(name = "isLend", nullable = false)
	public int getIsLend() {
		return this.isLend;
	}

	public void setIsLend(int isLend) {
		this.isLend = isLend;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceTableId))
			return false;
		InvoiceTableId castOther = (InvoiceTableId) other;

		return (this.getId() == castOther.getId()) && (this.getIncomeId() == castOther.getIncomeId())
				&& ((this.getInvoiceName() == castOther.getInvoiceName())
						|| (this.getInvoiceName() != null && castOther.getInvoiceName() != null
								&& this.getInvoiceName().equals(castOther.getInvoiceName())))
				&& ((this.getInvoiceContent() == castOther.getInvoiceContent())
						|| (this.getInvoiceContent() != null && castOther.getInvoiceContent() != null
								&& this.getInvoiceContent().equals(castOther.getInvoiceContent())))
				&& (this.getInvoiceNo() == castOther.getInvoiceNo())
				&& (this.getRequestUserId() == castOther.getRequestUserId())
				&& (this.getInvoiceAmount() == castOther.getInvoiceAmount())
				&& ((this.getOpenDate() == castOther.getOpenDate()) || (this.getOpenDate() != null
						&& castOther.getOpenDate() != null && this.getOpenDate().equals(castOther.getOpenDate())))
				&& (this.getOpenUserId() == castOther.getOpenUserId()) && (this.getIsLend() == castOther.getIsLend());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIncomeId();
		result = 37 * result + (getInvoiceName() == null ? 0 : this.getInvoiceName().hashCode());
		result = 37 * result + (getInvoiceContent() == null ? 0 : this.getInvoiceContent().hashCode());
		result = 37 * result + this.getInvoiceNo();
		result = 37 * result + this.getRequestUserId();
		result = 37 * result + (int) this.getInvoiceAmount();
		result = 37 * result + (getOpenDate() == null ? 0 : this.getOpenDate().hashCode());
		result = 37 * result + this.getOpenUserId();
		result = 37 * result + this.getIsLend();
		return result;
	}

}
