package com.cts.localtour.entity;
// Generated 2016-12-5 15:42:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PermissionTable generated by hbm2java
 */
@Entity
@Table(name = "permissionTable", catalog = "localtour")
public class PermissionTable implements java.io.Serializable {

	private int id;
	private String permissionName;
	private Boolean enable;
	private int permissionId;

	public PermissionTable() {
	}

	public PermissionTable(int id, int permissionId) {
		this.id = id;
		this.permissionId = permissionId;
	}

	public PermissionTable(int id, String permissionName, Boolean enable, int permissionId) {
		this.id = id;
		this.permissionName = permissionName;
		this.enable = enable;
		this.permissionId = permissionId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "permissionName", length = 16)
	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	@Column(name = "enable")
	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	@Column(name = "permissionId", nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

}
