package com.cts.localtour.entity;
// Generated 2017-6-29 10:52:58 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReimbursementTable generated by hbm2java
 */
@Entity
@Table(name = "reimbursementTable", catalog = "localtour")
public class ReimbursementTable implements java.io.Serializable {

	private Integer id;
	private int tourId;
	private BigDecimal headAmount;

	public ReimbursementTable() {
	}

	public ReimbursementTable(int tourId, BigDecimal headAmount) {
		this.tourId = tourId;
		this.headAmount = headAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tourId", nullable = false)
	public int getTourId() {
		return this.tourId;
	}

	public void setTourId(int tourId) {
		this.tourId = tourId;
	}

	@Column(name = "headAmount", nullable = false, precision = 11)
	public BigDecimal getHeadAmount() {
		return this.headAmount;
	}

	public void setHeadAmount(BigDecimal headAmount) {
		this.headAmount = headAmount;
	}

}
