package com.cts.localtour.entity;
// Generated 2017-2-28 14:40:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysUsageTable generated by hbm2java
 */
@Entity
@Table(name = "sysUsageTable", catalog = "localtour")
public class SysUsageTable implements java.io.Serializable {

	private Integer id;
	private String userRealName;
	private int tourCount;
	private int createCount;
	private int auditingCount;
	private int financeCount;
	private int canLendCount;
	private int ongoingCount;
	private int finishCount;
	private int balanceCount;
	private int reimbursementCount;
	private int verificationCount;
	private int settlementCount;

	public SysUsageTable() {
	}

	public SysUsageTable(String userRealName, int tourCount, int createCount, int auditingCount, int financeCount,
			int canLendCount, int ongoingCount, int finishCount, int balanceCount, int reimbursementCount,
			int verificationCount, int settlementCount) {
		this.userRealName = userRealName;
		this.tourCount = tourCount;
		this.createCount = createCount;
		this.auditingCount = auditingCount;
		this.financeCount = financeCount;
		this.canLendCount = canLendCount;
		this.ongoingCount = ongoingCount;
		this.finishCount = finishCount;
		this.balanceCount = balanceCount;
		this.reimbursementCount = reimbursementCount;
		this.verificationCount = verificationCount;
		this.settlementCount = settlementCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userRealName", nullable = false, length = 50)
	public String getUserRealName() {
		return this.userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}

	@Column(name = "tourCount", nullable = false)
	public int getTourCount() {
		return this.tourCount;
	}

	public void setTourCount(int tourCount) {
		this.tourCount = tourCount;
	}

	@Column(name = "createCount", nullable = false)
	public int getCreateCount() {
		return this.createCount;
	}

	public void setCreateCount(int createCount) {
		this.createCount = createCount;
	}

	@Column(name = "auditingCount", nullable = false)
	public int getAuditingCount() {
		return this.auditingCount;
	}

	public void setAuditingCount(int auditingCount) {
		this.auditingCount = auditingCount;
	}

	@Column(name = "financeCount", nullable = false)
	public int getFinanceCount() {
		return this.financeCount;
	}

	public void setFinanceCount(int financeCount) {
		this.financeCount = financeCount;
	}

	@Column(name = "canLendCount", nullable = false)
	public int getCanLendCount() {
		return this.canLendCount;
	}

	public void setCanLendCount(int canLendCount) {
		this.canLendCount = canLendCount;
	}

	@Column(name = "ongoingCount", nullable = false)
	public int getOngoingCount() {
		return this.ongoingCount;
	}

	public void setOngoingCount(int ongoingCount) {
		this.ongoingCount = ongoingCount;
	}

	@Column(name = "finishCount", nullable = false)
	public int getFinishCount() {
		return this.finishCount;
	}

	public void setFinishCount(int finishCount) {
		this.finishCount = finishCount;
	}

	@Column(name = "balanceCount", nullable = false)
	public int getBalanceCount() {
		return this.balanceCount;
	}

	public void setBalanceCount(int balanceCount) {
		this.balanceCount = balanceCount;
	}

	@Column(name = "reimbursementCount", nullable = false)
	public int getReimbursementCount() {
		return this.reimbursementCount;
	}

	public void setReimbursementCount(int reimbursementCount) {
		this.reimbursementCount = reimbursementCount;
	}

	@Column(name = "verificationCount", nullable = false)
	public int getVerificationCount() {
		return this.verificationCount;
	}

	public void setVerificationCount(int verificationCount) {
		this.verificationCount = verificationCount;
	}

	@Column(name = "settlementCount", nullable = false)
	public int getSettlementCount() {
		return this.settlementCount;
	}

	public void setSettlementCount(int settlementCount) {
		this.settlementCount = settlementCount;
	}

}
