package com.cts.localtour.entity;
// Generated 2017-4-24 10:58:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TourNoAscriptionTable generated by hbm2java
 */
@Entity
@Table(name = "tourNoAscriptionTable", catalog = "localtour")
public class TourNoAscriptionTable implements java.io.Serializable {

	private Integer id;
	private String header;
	private int deptId;

	public TourNoAscriptionTable() {
	}

	public TourNoAscriptionTable(String header, int deptId) {
		this.header = header;
		this.deptId = deptId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "header", nullable = false, length = 10)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "deptId", nullable = false)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

}
